services:
  rapamusic-web:
    image: 172.16.101.10/dockertoy/web:1
    ports:
    - '3000:3000'
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.role == web]

  rapamusic-was:
    image: 172.16.101.10/dockertoy/was:1
    ports:
    - '8080:8080'
    deploy:
      replicas: 2
      placement:
        constraints: [node.labels.role == was]

  rapamusic-db:
    image: 172.16.101.10/dockertoy/db:1
    deploy:
      placement:
        constraints: [node.labels.role == db]
